baseURL = 'https://hugo-theme-seiheki-template.vercel.app'      # 网站域名
languageCode = 'en-us'                                        # 网页语言
title = 'My New Hugo Site'                                    # 网站Title
theme = 'seiheki'

[markup]
  [markup.highlight]
    codeFences = true
    linenos = true
    linenosStyle = "inline"
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML" , "RSS" , "JSON"]

[permalinks]
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[params.Umami]                                                # Umami网站数据统计
  webpanel = ""                                               # 统计网站面板，空值默认为官网
  id = "84f6eb25-5dcd-4e2b-b500-37a6ac27f531"                 # 网站的Website ID，空值不开启统计

[params.Utterances]                                           # 添加Utterances评论
  repo = "Cicada000/Blog-Comments"                            # 你的评论仓库，空值不启用评论
