baseURL = 'https://seiheki-demo.cicada000.work'               # 网站域名
defaultContentLanguage = 'zh-cn'                              # 网页默认语言，目前支持zh-cn和en-us
title = 'Seiheki Demo Site'                                   # 网站Title，请同步更改i18n文件夹下配置
theme = 'seiheki'                                             # 主题名称
hasCJKLanguage = true                                         # 是否有CJK字符

[params]
    subtitle = "This is a demo site."                         # 网站副标题，请同步更改i18n文件夹下配置
    favicon = "https://www.cicada000.work/favicon.png"        # 网站Favicon 
    fancybox = true                                           # 开启图片灯箱
    paginate = 10                                             # 每页文章数目

[params.Umami]                                                # Umami网站数据统计
  webpanel = ""                                               # 统计网站面板，空值默认为官网
  id = "84f6eb25-5dcd-4e2b-b500-37a6ac27f531"                 # 网站的Website ID，空值不开启统计

[params.Utterances]                                           # 添加Utterances评论
  repo = "Cicada000/Blog-Comments"                            # 你的评论仓库，空值不启用评论

[markup]
  [markup.highlight]
    codeFences = true
    linenos = true
    linenosStyle = "inline"
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML" , "RSS" , "JSON"]

[permalinks]
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"